FROM node:16-alpine
RUN addgroup app && adduser -S -G app app
RUN mkdir /app && chown app:app /app
USER app
WORKDIR '/app'
COPY package.json .
RUN npm config set unsafe-perm true
RUN npm install --unsafe-perm=true --allow-root

COPY --chown=app:app . .
CMD ["npm", "run", "start"]