version: '3'
services:
  web:
    build:
      # Sets the context. In this case context is the root folder where DockerFile.dev is
      context: .
      # Docker file name here.
      dockerfile: Dockerfile.dev
    ports:
      # Port mapping localPort:containerPort
      - "3000:3000"
    volumes:
      # Do not map anything to this folder. Always use the folder from the container
      - /app/node_modules
      # Rest of the folders from "." (host machine) is mapped to "/app" (container)
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]